### ISSUE TITLE
make # of replicas configurable

### ISSUE THREAD

**Issue by PuntoDiGoccia** [spotinst/spotinst-kubernetes-helm-charts#30] opened 2021-07-30 09:54 UTC
**What would you like to be added?**
spotinst.replicas

**Why is this needed?**
During a rollover, due to a network problem, k8s was not able to pull the controller image.
Since the old controller was gone, we lost its functions completely and the cluster was not able to add nodes

**Comment by applike-ss** [comment] 2022-03-28 08:38
The described situation is a concern on our side as well.

Is the controller able to operate flawlessly with replicas?

If so i'd be happy to write a PR for this.

**Comment by applike-ss** [comment] 2022-05-02 08:23
@liranp do you possibly know? afaik the source code of the controller is not publicly available, so i couldn't check myself. It seems you were the last person merging a pr, so i assume you might be related to spotinst?

**Comment by drpebcak** [comment] 2022-07-06 17:29
Having the ability to run multiple replicas of this controller is pretty critical for us! We just had an incident yesterday where having replicas would have made recovery a lot easier.

**Comment by applike-ss** [comment] 2022-07-25 11:45
if the controllers source code was open source then i could make an educated guess whether simply adding replicas would be working. Now everyone is waiting for response from spotinst and nothing is happening. Would be nice if the communication from spotinst side would be improved!

**Comment by yinnonbar** [comment] 2022-07-27 13:48
Hi,
Sorry for the late delay.
The controller won't be able to operate flawlessly with multiple replicas and I’ll explain why.
Currently, it is designed to work as a singleton manager on the cluster.
The controller has 2 primary responsibilities - 
The first is to report to the cluster state of Spot’s Ocean and the required information about the resources.
For this purpose, it's fine for the controller to operate with multiple replicas as all of them would just override each other's reports.
This will lead to unnecessary reports and unnecessary traffic but won’t cause any damage to the cluster state or the data retrieved by Spot’s Ocean in order to operate and handle the cluster (if our scope is of course around 2 or some replicas).

On the other hand, having multiple replicas might cause troubles when interacting with the k8s API. 
The Spot k8s controller is receiving orders from Spot’s Ocean that are related to handling nodes and resources in the cluster, such as cordons, drain nodes, etc.
When the Spot k8s controller doesn’t run as a single controller, it might cause unexpected behavior in the cluster which will eventually lead to cases where the cluster is not managed properly as it should be by Ocean’s calculation.
We are expecting the Spot k8s controller to be a single component that is responsible for handling the orders received by Spot’s Ocean and reporting about the handling. For more than one replica, we might get into cases of race conditions or multiple actions being taken for one order.

In our docs, you can find the configuration of the controller that is causing it to be highly available:
https://docs.spot.io/ocean/tutorials/spot-kubernetes-controller/?id=high-availability

In order to better understand the case you encountered, could you please share the flow you had, step by step, and add the relevant logs if possible so we can further explore how we can address those cases?

**Comment by drpebcak** [comment] 2022-07-27 16:27
Having `system-node-critical` is expressly NOT HA. Typically controllers like this use leader election to ensure multiple replicas can run without overriding each other, while still having another instance running to immediately take action if there is a problem with the leader.

In my case, I had an incident where a majority of my nodes broke and were not able to take new workloads. This includes the node that was running the spot controller. When this happened, I had to force delete the spot controller pod to get it to try to reschedule elsewhere, but the nodes that were still healthy were already full of other workloads. Because of this, I had to evict some functional pods and worsen my outage in order to get spot running again so that I could get the nodes I needed to reschedule the workloads from the broken nodes.

**Comment by applike-ss** [comment] 2022-07-29 07:22
> Having system-node-critical is expressly NOT HA.

This (in other words) i also wrote to them in my initial support request.

> Typically controllers like this use leader election to ensure multiple replicas can run without overriding each other, while still having another instance running to immediately take action if there is a problem with the leader.

This is exactly what i would propose to spotinst too. @yinnonbar  Please implement this. It can not be that a software for High availability clusters is itself not high available and by that potentially takes down critical production systems.

**Comment by applike-ss** [comment] 2022-08-10 06:10
@yinnonbar It would be great to get any feedback from your side, if you plan to adjust the software.

**Comment by yinnonbar** [comment] 2022-08-14 10:13
Hi,
I would like to share some more information about our high availability mechanism.
The controller is configured to work with the following configuration:

- System-node-critical as a priority class -If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the controller Pod possible. Meaning, that should cover a case where a scale-up is not possible for any reason.

- No resource request - That would allow the controller pod to be scheduled on any node in the cluster since there are no request restrictions.

- Pod Anti Affinity with Spot’s ocean k8s controller - restrict the option that 2 Spot Ocean k8s controllers will be scheduled on one the same node. For example, in case the controller does not report a heartbeat and the health check fails, k8s will automatically create a new pod. The new pod will be scheduled on a different node in order to eliminate the option that the issue is with the original node. We try to recreate the controller pod up to 5 times.

All of the above are used in order to make sure that Spot’s ocean k8s controller is always running.
In addition, we also have a notification mechanism once the Ocean k8s controller is not reporting a heartbeat in order for you to address the issue immediately.
In addition, if you are using Prometheus, we also have a Spot Ocean metric exporter that indicates whether the Ocean k8s controller is running or not ([Link](https://docs.spot.io/ocean/tools-and-integrations/prometheus/README)).

With that being said, it is possible to run more than 1 replica to the controller. A leader mechanism will automatically handle the replicas and select one as the leader.
Please note, that for example in case you have 2 replicas that are running on different nodes and both of them are interrupted at the same time - the situation will be the same as you described in your previous comment. 

Our recommendation is to run only with 1 replica as best practice, however, it is possible to use more than 1 replica.

Thank you for your feedback and we look forward to hearing back from you soon.

**Comment by applike-ss** [comment] 2022-08-15 13:24
Hi,

thanks for coming back to clarify things.
Here's some questions that your last comment brings up in my mind:

1. Is the leader election a newly added feature? You did mention in https://github.com/spotinst/spotinst-kubernetes-helm-charts/issues/30#issuecomment-1196787593 that it will cause troubles in the calculation. 
2. With all the requirements for a HA setup of the spotinst controller being possible, why do you still recommend not to do it?

**Comment by yinnonbar** [comment] 2022-08-16 12:51
Hi,
I would like to elaborate on my last comment. The leader election is not a new mechanism in our controller. After testing the HA mechanism described above with our clients and internally, we decided it’s indeed reliable and covers a wide range of events that might affect the controller.
Although the leader election was developed as well, it was not used by clients since the current mechanism fulfilled the controller high availability requests. Ocean manages thousands of clusters and we tested it widely, and the mechanism maintains HA for the controller.  
Regarding our recommendation, the reason is that the current mechanism was widely used and proved himself as HA.
Following your request we made some additional testings to the leader election mechanism and as mentioned it should work properly.
In case you wish to test it or you have any other feedbacks we will be happy to collaborate and further discuss it.
Have a great day.

**Comment by applike-ss** [comment] 2022-08-16 13:02
Thank you, i created a PR to allow everyone to configure their replica count

**Comment by applike-ss** [comment] 2022-08-24 06:01
@yinnonbar can you approve and merge my PR if you agree with my changes or let me know what's holding you back otherwise?

**Comment by applike-ss** [comment] 2022-09-09 08:16
I'm in direct contact with spotinst on this and we discussed yesterday that my PR will be merged after we did a successful test of the spotinst controller with multiple replicas.
Right now it is looking promising, but we'll leave it running for a week and report back then.

**Comment by applike-ss** [comment] 2022-09-15 06:14
We've let it run with 3 replicas for a week now and we could not see any unexpected effects.

/lgtm

**Closed as completed** 2022-09-20 14:15 UTC

**Comment by marcuz** [comment] 2022-09-21 09:38
@yinnonbar any ETA on when the chart `1.0.105` will be released?
